name: Build g3man


on:
  push:
    branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, artifact-name: g3man-linux-amd64 }
          - { os: windows-latest, artifact-name: g3man-windows-amd64 }

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MSYS2
        id: msys2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2.30.0
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-libadwaita

      # The python script is used to build because it passes in the above environment variable
      # and also bundles a readme. Probably stupid but why not
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12' 

      - name: Publish
        env:
          MINGWROOT: ${{ steps.msys2.outputs.msys2-location }}\mingw64
        run: |
          cd g3man/Publishing
          python3 publish.py
          ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix['artifact-name'] }}
          path: g3man/Publishing/package/bin